FROM node:20-alpine AS build
WORKDIR /workspace
ARG APP_NAME
ARG VITE_API_BASE_URL
ENV VITE_API_BASE_URL=${VITE_API_BASE_URL}
COPY package.json package-lock.json ./
COPY apps ./apps
COPY packages ./packages
RUN npm ci
RUN npm --workspace apps/${APP_NAME} run build

FROM nginx:1.27-alpine
COPY deploy/nginx-spa.conf /etc/nginx/conf.d/default.conf
ARG APP_NAME
COPY --from=build /workspace/apps/${APP_NAME}/dist /usr/share/nginx/html
EXPOSE 80
