package com.company.gptplus.inventory;

import com.company.gptplus.common.BizException;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.jdbc.datasource.DriverManagerDataSource;

import javax.sql.DataSource;

import static org.assertj.core.api.Assertions.assertThat;
import static org.assertj.core.api.Assertions.assertThatThrownBy;

class InventoryReservationServiceTests {
    private JdbcTemplate jdbcTemplate;
    private InventoryReservationService service;

    @BeforeEach
    void setUp() {
        DataSource dataSource = new DriverManagerDataSource("jdbc:h2:mem:inventory_test;MODE=PostgreSQL;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE", "sa", "");
        jdbcTemplate = new JdbcTemplate(dataSource);
        jdbcTemplate.execute("drop table if exists inventory_account");
        jdbcTemplate.execute("""
                create table inventory_account (
                  id bigint generated by default as identity primary key,
                  batch_no varchar(64) not null,
                  product_id bigint not null,
                  resource_account varchar(255) not null,
                  resource_password_cipher varchar(512) not null,
                  status varchar(32) not null default 'AVAILABLE',
                  assigned_order_no varchar(64),
                  assigned_user_id bigint,
                  assigned_at timestamp,
                  remark varchar(500),
                  created_at timestamp not null default current_timestamp,
                  updated_at timestamp not null default current_timestamp
                )
                """);
        service = new InventoryReservationService(jdbcTemplate);
    }

    @Test
    void reserveMovesAvailableStockToReservedForOrder() {
        insertInventory(1L, "a@example.com");

        service.reserve(1L, "O1", 10L, 1);

        Integer available = countByStatus("AVAILABLE");
        Integer reserved = countByStatus("RESERVED");
        assertThat(available).isZero();
        assertThat(reserved).isEqualTo(1);
        assertThat(jdbcTemplate.queryForObject("select assigned_order_no from inventory_account", String.class)).isEqualTo("O1");
    }

    @Test
    void releaseReturnsReservedStockToAvailable() {
        insertInventory(1L, "a@example.com");
        service.reserve(1L, "O1", 10L, 1);

        service.release("O1");

        assertThat(countByStatus("AVAILABLE")).isEqualTo(1);
        assertThat(jdbcTemplate.queryForObject("select assigned_order_no from inventory_account", String.class)).isNull();
    }

    @Test
    void claimReservedDeliversOnlyTheOrdersOwnStock() {
        insertInventory(1L, "a@example.com");
        insertInventory(1L, "b@example.com");
        service.reserve(1L, "O1", 10L, 1);
        service.reserve(1L, "O2", 11L, 1);

        service.claimReserved("O1", 10L);

        assertThat(countByStatus("ASSIGNED")).isEqualTo(1);
        assertThat(countByStatus("RESERVED")).isEqualTo(1);
        assertThat(jdbcTemplate.queryForObject("""
                select assigned_order_no from inventory_account where status='ASSIGNED'
                """, String.class)).isEqualTo("O1");
    }

    @Test
    void ensureReservedOnlyFillsMissingReservations() {
        insertInventory(1L, "a@example.com");
        insertInventory(1L, "b@example.com");
        service.reserve(1L, "O1", 10L, 1);

        service.ensureReserved(1L, "O1", 10L, 2);

        assertThat(countByStatus("RESERVED")).isEqualTo(2);
    }

    @Test
    void claimForOrderCanReserveAndClaimLegacyOrderWithoutReservation() {
        insertInventory(1L, "a@example.com");

        service.claimForOrder(1L, "OLD_ORDER", 10L);

        assertThat(countByStatus("ASSIGNED")).isEqualTo(1);
        assertThat(jdbcTemplate.queryForObject("select assigned_order_no from inventory_account", String.class)).isEqualTo("OLD_ORDER");
    }

    @Test
    void reserveThrowsAndDoesNotLeavePartialReservationWhenStockIsInsufficient() {
        insertInventory(1L, "a@example.com");

        assertThatThrownBy(() -> service.reserve(1L, "O1", 10L, 2))
                .isInstanceOf(BizException.class)
                .hasMessage("库存不足");

        assertThat(countByStatus("AVAILABLE")).isEqualTo(1);
        assertThat(countByStatus("RESERVED")).isZero();
    }

    private void insertInventory(long productId, String account) {
        jdbcTemplate.update("""
                insert into inventory_account(batch_no, product_id, resource_account, resource_password_cipher, status)
                values ('B1', ?, ?, 'ENC:test', 'AVAILABLE')
                """, productId, account);
    }

    private Integer countByStatus(String status) {
        return jdbcTemplate.queryForObject("select count(*) from inventory_account where status=?", Integer.class, status);
    }
}
