CREATE TABLE IF NOT EXISTS sys_user (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  username VARCHAR(64) NOT NULL UNIQUE,
  password_hash VARCHAR(255) NOT NULL,
  email VARCHAR(128),
  status VARCHAR(32) NOT NULL DEFAULT 'ENABLED',
  register_ip VARCHAR(64),
  last_login_at TIMESTAMP,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX IF NOT EXISTS idx_sys_user_email ON sys_user(email);

CREATE TABLE IF NOT EXISTS sys_admin (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  username VARCHAR(64) NOT NULL UNIQUE,
  password_hash VARCHAR(255) NOT NULL,
  role_code VARCHAR(64) NOT NULL,
  status VARCHAR(32) NOT NULL DEFAULT 'ENABLED',
  last_login_at TIMESTAMP,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX IF NOT EXISTS idx_sys_admin_role_code ON sys_admin(role_code);

CREATE TABLE IF NOT EXISTS product (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  product_code VARCHAR(64) NOT NULL UNIQUE,
  name VARCHAR(128) NOT NULL,
  subtitle VARCHAR(255),
  cover_url VARCHAR(512),
  price NUMERIC(10,2) NOT NULL,
  original_price NUMERIC(10,2),
  delivery_type VARCHAR(32) NOT NULL,
  status VARCHAR(32) NOT NULL DEFAULT 'OFF_SHELF',
  description TEXT,
  stock_display_mode VARCHAR(32) NOT NULL DEFAULT 'HIDE',
  sort INT NOT NULL DEFAULT 0,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
ALTER TABLE product ADD COLUMN IF NOT EXISTS product_code VARCHAR(64);
ALTER TABLE product ADD COLUMN IF NOT EXISTS name VARCHAR(128);
ALTER TABLE product ADD COLUMN IF NOT EXISTS subtitle VARCHAR(255);
ALTER TABLE product ADD COLUMN IF NOT EXISTS cover_url VARCHAR(512);
ALTER TABLE product ADD COLUMN IF NOT EXISTS price NUMERIC(10,2);
ALTER TABLE product ADD COLUMN IF NOT EXISTS original_price NUMERIC(10,2);
ALTER TABLE product ADD COLUMN IF NOT EXISTS delivery_type VARCHAR(32) DEFAULT 'CDKEY';
ALTER TABLE product ADD COLUMN IF NOT EXISTS status VARCHAR(32) DEFAULT 'OFF_SHELF';
ALTER TABLE product ADD COLUMN IF NOT EXISTS description TEXT;
ALTER TABLE product ADD COLUMN IF NOT EXISTS stock_display_mode VARCHAR(32) DEFAULT 'HIDE';
ALTER TABLE product ADD COLUMN IF NOT EXISTS sort INT DEFAULT 0;
ALTER TABLE product ADD COLUMN IF NOT EXISTS created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE product ADD COLUMN IF NOT EXISTS updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP;
CREATE INDEX IF NOT EXISTS idx_product_status ON product(status);
CREATE INDEX IF NOT EXISTS idx_product_sort ON product(sort);

CREATE TABLE IF NOT EXISTS order_info (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  order_no VARCHAR(64) NOT NULL UNIQUE,
  user_id BIGINT NOT NULL,
  product_id BIGINT NOT NULL,
  product_name_snapshot VARCHAR(128) NOT NULL,
  price_snapshot NUMERIC(10,2) NOT NULL,
  quantity INT NOT NULL DEFAULT 1,
  amount NUMERIC(10,2) NOT NULL,
  pay_amount NUMERIC(10,2) NOT NULL,
  order_status VARCHAR(32) NOT NULL DEFAULT 'UNPAID',
  pay_status VARCHAR(32) NOT NULL DEFAULT 'UNPAID',
  delivery_status VARCHAR(32) NOT NULL DEFAULT 'PENDING',
  client_type VARCHAR(32) NOT NULL DEFAULT 'WEB',
  closed_reason VARCHAR(255),
  paid_at TIMESTAMP,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
ALTER TABLE order_info ADD COLUMN IF NOT EXISTS order_no VARCHAR(64);
ALTER TABLE order_info ADD COLUMN IF NOT EXISTS user_id BIGINT;
ALTER TABLE order_info ADD COLUMN IF NOT EXISTS product_id BIGINT;
ALTER TABLE order_info ADD COLUMN IF NOT EXISTS product_name_snapshot VARCHAR(128);
ALTER TABLE order_info ADD COLUMN IF NOT EXISTS price_snapshot NUMERIC(10,2);
ALTER TABLE order_info ADD COLUMN IF NOT EXISTS quantity INT DEFAULT 1;
ALTER TABLE order_info ADD COLUMN IF NOT EXISTS amount NUMERIC(10,2);
ALTER TABLE order_info ADD COLUMN IF NOT EXISTS pay_amount NUMERIC(10,2);
ALTER TABLE order_info ADD COLUMN IF NOT EXISTS order_status VARCHAR(32) DEFAULT 'UNPAID';
ALTER TABLE order_info ADD COLUMN IF NOT EXISTS pay_status VARCHAR(32) DEFAULT 'UNPAID';
ALTER TABLE order_info ADD COLUMN IF NOT EXISTS delivery_status VARCHAR(32) DEFAULT 'PENDING';
ALTER TABLE order_info ADD COLUMN IF NOT EXISTS client_type VARCHAR(32) DEFAULT 'WEB';
ALTER TABLE order_info ADD COLUMN IF NOT EXISTS closed_reason VARCHAR(255);
ALTER TABLE order_info ADD COLUMN IF NOT EXISTS paid_at TIMESTAMP;
ALTER TABLE order_info ADD COLUMN IF NOT EXISTS created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE order_info ADD COLUMN IF NOT EXISTS updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP;
CREATE INDEX IF NOT EXISTS idx_order_info_user_created ON order_info(user_id, created_at);
CREATE INDEX IF NOT EXISTS idx_order_info_product_id ON order_info(product_id);
CREATE INDEX IF NOT EXISTS idx_order_info_pay_status ON order_info(pay_status);
CREATE INDEX IF NOT EXISTS idx_order_info_order_status ON order_info(order_status);

CREATE TABLE IF NOT EXISTS payment_record (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  payment_no VARCHAR(64) NOT NULL UNIQUE,
  order_no VARCHAR(64) NOT NULL,
  channel VARCHAR(32) NOT NULL,
  amount NUMERIC(10,2) NOT NULL,
  status VARCHAR(32) NOT NULL DEFAULT 'INIT',
  third_party_trade_no VARCHAR(128),
  callback_raw TEXT,
  paid_at TIMESTAMP,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX IF NOT EXISTS idx_payment_record_order_no ON payment_record(order_no);
CREATE INDEX IF NOT EXISTS idx_payment_record_trade_no ON payment_record(third_party_trade_no);
CREATE INDEX IF NOT EXISTS idx_payment_record_status ON payment_record(status);

CREATE TABLE IF NOT EXISTS cdk_record (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  cdk_code VARCHAR(64) NOT NULL UNIQUE,
  product_id BIGINT NOT NULL,
  order_id BIGINT,
  order_no VARCHAR(64),
  owner_user_id BIGINT,
  status VARCHAR(32) NOT NULL DEFAULT 'UNBOUND',
  expired_at TIMESTAMP,
  used_at TIMESTAMP,
  used_by_user_id BIGINT,
  delivery_snapshot TEXT,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX IF NOT EXISTS idx_cdk_record_owner_user_id ON cdk_record(owner_user_id);
CREATE INDEX IF NOT EXISTS idx_cdk_record_order_no ON cdk_record(order_no);
CREATE INDEX IF NOT EXISTS idx_cdk_record_status ON cdk_record(status);
CREATE INDEX IF NOT EXISTS idx_cdk_record_product_id ON cdk_record(product_id);

CREATE TABLE IF NOT EXISTS inventory_account (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  batch_no VARCHAR(64) NOT NULL,
  product_id BIGINT NOT NULL,
  resource_account VARCHAR(255) NOT NULL,
  resource_password_cipher VARCHAR(512) NOT NULL,
  status VARCHAR(32) NOT NULL DEFAULT 'AVAILABLE',
  assigned_order_no VARCHAR(64),
  assigned_user_id BIGINT,
  assigned_at TIMESTAMP,
  remark VARCHAR(500),
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  UNIQUE(product_id, resource_account)
);
ALTER TABLE inventory_account ADD COLUMN IF NOT EXISTS batch_no VARCHAR(64);
ALTER TABLE inventory_account ADD COLUMN IF NOT EXISTS product_id BIGINT;
ALTER TABLE inventory_account ADD COLUMN IF NOT EXISTS resource_account VARCHAR(255);
ALTER TABLE inventory_account ADD COLUMN IF NOT EXISTS resource_password_cipher VARCHAR(512);
ALTER TABLE inventory_account ADD COLUMN IF NOT EXISTS status VARCHAR(32) DEFAULT 'AVAILABLE';
ALTER TABLE inventory_account ADD COLUMN IF NOT EXISTS assigned_order_no VARCHAR(64);
ALTER TABLE inventory_account ADD COLUMN IF NOT EXISTS assigned_user_id BIGINT;
ALTER TABLE inventory_account ADD COLUMN IF NOT EXISTS assigned_at TIMESTAMP;
ALTER TABLE inventory_account ADD COLUMN IF NOT EXISTS remark VARCHAR(500);
ALTER TABLE inventory_account ADD COLUMN IF NOT EXISTS created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE inventory_account ADD COLUMN IF NOT EXISTS updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP;
CREATE INDEX IF NOT EXISTS idx_inventory_account_product_status ON inventory_account(product_id, status);
CREATE INDEX IF NOT EXISTS idx_inventory_account_batch_no ON inventory_account(batch_no);
CREATE INDEX IF NOT EXISTS idx_inventory_account_assigned_order_no ON inventory_account(assigned_order_no);

CREATE TABLE IF NOT EXISTS redeem_record (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  redeem_no VARCHAR(64) NOT NULL UNIQUE,
  user_id BIGINT NOT NULL,
  cdk_id BIGINT,
  cdk_code VARCHAR(64) NOT NULL,
  product_id BIGINT,
  inventory_id BIGINT,
  resource_account VARCHAR(255),
  result VARCHAR(32) NOT NULL,
  fail_reason VARCHAR(255),
  client_ip VARCHAR(64),
  device_fingerprint VARCHAR(255),
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
ALTER TABLE redeem_record ADD COLUMN IF NOT EXISTS resource_account VARCHAR(255);
CREATE INDEX IF NOT EXISTS idx_redeem_record_user_created ON redeem_record(user_id, created_at);
CREATE INDEX IF NOT EXISTS idx_redeem_record_cdk_code ON redeem_record(cdk_code);
CREATE INDEX IF NOT EXISTS idx_redeem_record_resource_account ON redeem_record(resource_account);
CREATE INDEX IF NOT EXISTS idx_redeem_record_result ON redeem_record(result);

CREATE TABLE IF NOT EXISTS risk_event (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  event_type VARCHAR(64) NOT NULL,
  user_id BIGINT,
  client_ip VARCHAR(64),
  device_fingerprint VARCHAR(255),
  hit_rule VARCHAR(128),
  action_result VARCHAR(64) NOT NULL,
  detail_json TEXT,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX IF NOT EXISTS idx_risk_event_event_type ON risk_event(event_type);
CREATE INDEX IF NOT EXISTS idx_risk_event_user_id ON risk_event(user_id);
CREATE INDEX IF NOT EXISTS idx_risk_event_client_ip ON risk_event(client_ip);
CREATE INDEX IF NOT EXISTS idx_risk_event_created_at ON risk_event(created_at);

CREATE TABLE IF NOT EXISTS admin_operation_log (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  admin_id BIGINT NOT NULL,
  module VARCHAR(64) NOT NULL,
  operation_type VARCHAR(64) NOT NULL,
  target_id VARCHAR(64),
  before_json TEXT,
  after_json TEXT,
  client_ip VARCHAR(64),
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
ALTER TABLE admin_operation_log ADD COLUMN IF NOT EXISTS admin_id BIGINT;
ALTER TABLE admin_operation_log ADD COLUMN IF NOT EXISTS module VARCHAR(64);
ALTER TABLE admin_operation_log ADD COLUMN IF NOT EXISTS operation_type VARCHAR(64);
ALTER TABLE admin_operation_log ADD COLUMN IF NOT EXISTS target_id VARCHAR(64);
ALTER TABLE admin_operation_log ADD COLUMN IF NOT EXISTS before_json TEXT;
ALTER TABLE admin_operation_log ADD COLUMN IF NOT EXISTS after_json TEXT;
ALTER TABLE admin_operation_log ADD COLUMN IF NOT EXISTS client_ip VARCHAR(64);
ALTER TABLE admin_operation_log ADD COLUMN IF NOT EXISTS created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP;
CREATE INDEX IF NOT EXISTS idx_admin_operation_log_admin_created ON admin_operation_log(admin_id, created_at);
CREATE INDEX IF NOT EXISTS idx_admin_operation_log_module ON admin_operation_log(module);

CREATE TABLE IF NOT EXISTS system_config (
  config_key VARCHAR(128) PRIMARY KEY,
  config_value TEXT,
  encrypted BOOLEAN NOT NULL DEFAULT FALSE,
  remark VARCHAR(255),
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS verification_code_query_log (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id BIGINT NOT NULL,
  resource_account VARCHAR(255) NOT NULL,
  cdk_code VARCHAR(64),
  result VARCHAR(32) NOT NULL,
  code_value VARCHAR(16),
  message_subject VARCHAR(500),
  fail_reason VARCHAR(255),
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
ALTER TABLE verification_code_query_log ADD COLUMN IF NOT EXISTS cdk_code VARCHAR(64);
CREATE INDEX IF NOT EXISTS idx_verification_code_query_user_created ON verification_code_query_log(user_id, created_at);
CREATE INDEX IF NOT EXISTS idx_verification_code_query_account ON verification_code_query_log(resource_account);
CREATE INDEX IF NOT EXISTS idx_verification_code_query_cdk_code ON verification_code_query_log(cdk_code);

CREATE TABLE IF NOT EXISTS email_verification_code (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  email VARCHAR(128) NOT NULL,
  code_value VARCHAR(16) NOT NULL,
  scene VARCHAR(32) NOT NULL,
  status VARCHAR(32) NOT NULL DEFAULT 'UNUSED',
  expired_at TIMESTAMP NOT NULL,
  used_at TIMESTAMP,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX IF NOT EXISTS idx_email_verification_email_scene ON email_verification_code(email, scene, created_at);
